Auction/Controllers/AuctionController.cs
using Auction.Models.DBModels;
using Auction.Models.ViewModels;
using Auction.Service;
using CloudinaryDotNet.Actions;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Auction.Models;
using static Azure.Core.HttpHeader;
using Microsoft.AspNetCore.Http.HttpResults;

namespace AuctionController.Controllers
{
    public class AuctionController : Controller
    {
        private readonly DBService dbService;
        private readonly CloudinaryService _cloudinaryService;
        private readonly Notification _notification;
        private readonly AutoBidStorage _autoBidStorage;
        public AuctionController(DBService _bdService, CloudinaryService cloudinaryService , Notification notification, AutoBidStorage autoBidStorage)
        {
            dbService = _bdService;
            _cloudinaryService = cloudinaryService;
            _notification = notification;
            _autoBidStorage = autoBidStorage;
        }

        [Route("Auction/InfoLot/{idLot?}")]
        public async Task<IActionResult> InfoLot(int ?idLot)
        {

            await dbService.AuctionService.IncrementView(idLot);
            Lot lot = await dbService.AuctionService.GetLot(idLot);

            return View(lot);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> GetMyLots()
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var lots = await dbService.AuctionService.GetMyLots(userId);

            var myLots = lots.Select(l => new
            {
                LotId = l.LotId,
                Title = l.Title,
                CurrentBid = l.CurrentPrice
            });

            return Json(new { success = true, myLots = myLots });
        }

        [HttpPost]
        public async Task<IActionResult> NewBidLot(int? idLot, int? newBid)
        {
            if(!User.Identity.IsAuthenticated)
                return Json(new { success = false, errorMessage = "To place bets, you need to register or log in to your account!" });

            if (idLot == null) 
                return Json(new { success = false, errorMessage = "Error, item not found." });

            if (newBid == null)
                return Json(new { success = false, errorMessage = "Select a new bid!" });

            Lot lot = await dbService.AuctionService.GetLot(idLot);

            if(newBid <= lot.CurrentPrice) return Json(new { success = false, errorMessage = "The bid must be higher than the previous one!" });

            if (lot.EndTime <= DateTime.Now) return Json(new { success = false, errorMessage = "Time for betting is over!" });

            if (!await dbService.AuctionService.NewBidLot(idLot, newBid, int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))))
                return Json(new { success = false, errorMessage = "Select a new bid!" });

            string userName = User.FindFirstValue(ClaimTypes.Name);

            await _notification.SendAuctionNewBidMessage(idLot.ToString(), userName, newBid.ToString());

            return Json(new { success = true });
        }

        [HttpPost]
        public async Task<IActionResult> AutoBid(int? idLot, int? maxBid, int? rateBid)
        {
            if (!User.Identity.IsAuthenticated)
                return Json(new { success = false, errorMessage = "To place bets, you need to register or log in to your account!" });

            if (!idLot.HasValue)
                return Json(new { success = false, errorMessage = "Error, item not found." });


            if (!maxBid.HasValue || !rateBid.HasValue)
                return Json(new { success = false, errorMessage = "Fill in all fields!" });

            Lot lot = await dbService.AuctionService.GetLot(idLot);

            if (lot.EndTime <= DateTime.Now) 
                return Json(new { success = false, errorMessage = "Time for betting is over!" });

            if (maxBid <= lot.CurrentPrice) 
                return Json(new { success = false, errorMessage = "The bid must be higher than the previous one!" });

            if (rateBid > maxBid)
                return Json(new { success = false, errorMessage = "Rate bid cannot be higher than the maximum!" });

            int idUser = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if(! _autoBidStorage.AddAutoBid(idLot.Value, idUser, maxBid.Value, rateBid.Value))
                return Json(new { success = false, errorMessage = "An error occurred while processing the request!" });

            return Json(new { success = true });
        }

        public async Task<IActionResult> GetAllLots()
        {
            var filterParams = new LotFilterParams
            {
                Size = 20,
                DateTime = DateTime.Now
            };

            return View(await dbService.AuctionService.GetAllLots(filterParams));
        }

        [HttpPost]
        public async Task<IActionResult> LoadNewLots(int? idLastLot, DateTime? dateTime, int? price, string? location, bool? isPopular)
        {
            if(dateTime == null) dateTime = DateTime.Now;

            var filterParams = new LotFilterParams
            {
                Size = 20,
                DateTime = dateTime,
                Price = price,
                Location = location,
                IdLastLot = idLastLot,
                IsPopular = isPopular
            };

            var lots = await dbService.AuctionService.GetAllLots(filterParams);

            if(lots == null) 
                return Json(new { success = false, errorMessage = "Looks like there was an error loading the lots, or they ran out." });

            var lotsDto = lots.Select(lot => new {
                LotId = lot.LotId,
                Title = lot.Title,
                EndTime = lot.EndTime.ToString("yyyy-MM-ddTHH:mm:ss"),
                CurrentPrice = lot.CurrentPrice,
                Location = lot.Location,
                ImgPath = lot.ImgPath
            }).ToList();

            if(lotsDto == null || lotsDto.Count == 0)
                return Json(new { success = true, errorMessage = "There are no more lots!" });

            return Json(new { success = true, lots = lotsDto });
        }

        [Authorize]
        [HttpGet]
        public IActionResult SellLot()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SellLot(CreateLotView model, List<IFormFile>? additionalPhotos)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage)
                    .ToList();

                return Json(new { success = false, errorMessage = errors });
            }

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var uploadResults = new List<ImageUploadResult>();

            var uploadResultMain = await _cloudinaryService.UploadImageAsync(model.ImgPath, $"lots/user - {userId}");

            Lot lot = new Lot
            {
                Title = model.Title,
                ImgPath = uploadResultMain.SecureUrl.ToString(),
                Description = model.Description,
                StartPrice = model.StartPrice,
                EndTime = model.EndTime,
                Location = model.Location,
                CreatedAt = DateTime.Now,
                UserId = int.Parse(userId)
            };

            if(!await dbService.AuctionService.AddLot(lot))
            {
                return Json(new { success = false, errorMessage = "error when adding your lot to the database!" });
            }

            if(additionalPhotos != null && additionalPhotos.Count != 0)
            {
                foreach (var photo in additionalPhotos)
                {
                    if (photo.Length > 0)
                    {
                        // Загрузка фото в папку пользователя на Cloudinary
                        var uploadResult = await _cloudinaryService.UploadImageAsync(photo, $"lots/user - {userId}");
                        uploadResults.Add(uploadResult);
                    }
                }

                List<ImgLot> images = new List<ImgLot>();

                // Сохранение путей к загруженным фотографиям в базу данных
                foreach (var result in uploadResults)
                {
                    var imgPath = result.SecureUrl.ToString();
                    images.Add(new ImgLot { ImgPath = imgPath, LotId = lot.LotId });
                }

                if (!await dbService.AuctionService.AddImgLots(images))
                {
                    return Json(new { success = false, errorMessage = "error when adding your photos to the database!" });
                }
            }

            return Json(new { success = true });
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ChangeLot(int? idLot)
        {
            int IdUser = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

            Lot lot = await dbService.AuctionService.GetLot(idLot);

            if (IdUser != lot.UserId) return View("~/Views/Home/ErrorMessage.cshtml", "You do not have permission to edit this lot!");

            return View(lot);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeLot(Lot? lot, List<FileUploadModel>? additionalPhotos, IFormFile? imgMainPath)
        {
            if (!ModelState.IsValid)
            {
                var missingFields = new List<string>();

                if (string.IsNullOrWhiteSpace(lot.Title))
                {
                    missingFields.Add("Title");
                }

Auction/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    var IdUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var userName = User.FindFirstValue(ClaimTypes.Name);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auction</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Auction.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Auction</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auction" asp-action="GetAllLots">View lots</a>
                        </li>
                    </ul>


                    @if (User.Identity.IsAuthenticated)
                    {
                        <!-- drop menu Auction -->
                        <div class="nav-item dropdown">
                            <a class="nav-link text-light text-decoration-none text-inherit" href="#" id="dropdownMenuAuction" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-bag-fill" viewBox="0 0 16 16">
                                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4z" />
                                </svg>
                            </a>

                            <ul class="dropdown-menu alert-warning" aria-labelledby="dropdownMenuAuction">
                                <li><h6 class="dropdown-header">View lots:</h6></li>
                                <li><a class="dropdown-item" href="/Auction/GetAllLots">Look</a></li>

                                <li><h6 class="dropdown-header">Sell the lot:</h6></li>
                                <li><a class="dropdown-item" href="/Auction/SellLot">Sell</a></li>

                                <li><h6 class="dropdown-header">My lots:</h6></li>
                                <li><a class="getMyLots dropdown-item" href="#">Look</a></li>
                            </ul>
                        </div>
                        <!-- drop menu Accaunt -->
                        <div class="nav-item dropdown">
                            <a class="nav-link text-light text-decoration-none text-inherit" href="#" id="dropdownMenuAccaunt" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user text-light">
                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                    <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                            </a>

                            <ul class="dropdown-menu alert-warning" aria-labelledby="dropdownMenuAccaunt">
                                <li><a class="dropdown-item" href="/User/MyPage?UserId=@IdUser">My page</a></li>
                                
                                <li><a class="dropdown-item" href="/Account/Clouse">Log out</a></li>

                                <li>
                                    <a class="dropdown-item" href="/User/MyMessage">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-chat-dots-fill" viewBox="0 0 16 16">
                                            <path d="M16 8c0 3.866-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7M5 8a1 1 0 1 0-2 0 1 1 0 0 0 2 0m4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0m3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
                                        </svg>
                                    </a>
                                </li>
                            </ul>
                        </div>

                        <div class="alert alert-light my-0 py-1">
                            <i class="bi bi-person-circle"></i>
                            <span>@userName</span>
                        </div>
                    }
                    else
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#formAccauntAuthorizationModal">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn btn-warning text-dark ms-2" href="#" data-bs-toggle="modal" data-bs-target="#formAccauntRegistrationModal">Register</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="notificationContainer" class="fixed-top p-3">
        <!-- Контейнер для уведомлений -->
        <div id="notificationSystemAlert" class="alert alert-info" style="display: none;"></div>

    </div>

    <footer class="border-top footer bg-dark text-white-50">
        <div class="container text-center">
            &copy; 2024 - Auction - <a class="text-decoration-none text-warning" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/observer.js" asp-append-version="true"></script>
    <script src="~/js/lot.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.9/signalr.min.js"></script>

    <script src="~/js/messageAuction.js"></script>
    <script src="~/js/messagePersonalChat.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

<partial name="/Views/Account/_AccountRegisration.cshtml" model="new User()" />
<partial name="/Views/Account/_AccountAuthorization.cshtml" />

</html>

<div class="modal fade" id="myLotsModal" tabindex="-1" aria-labelledby="myLotsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myLotsModalLabel">My Lots</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul id="myLotsList">
                    <!-- Список лотов -->
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Clouse</button>
            </div>
        </div>
    </div>
</div>